### ISSUE TITLE
Default Value Type for prometheus-to-sd

### ISSUE THREAD

**Issue by filipe-cantarelli** [GoogleCloudPlatform/k8s-stackdriver#52]
The current default type is ["INT64"](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/translator/translator.go#L282)

This is breaking floating point metrics such as: "custom.googleapis.com/kube-state-metrics/kube_pod_container_resource_requests_cpu_cores"

Since the variable that holds the Value is of type float64 already, I think the best candidate for default type should be "DOUBLE" instead of "INT64".

**Comment by loburm** [comment]
It's a duplicate of: https://github.com/kubernetes/contrib/issues/2655

**Comment by loburm** [comment]
Oh, It's in wrong repository.

It actually have a sense to leave this one.

**Comment by acondrat** [comment]
I was having the same issue and the default type change seems to be a reasonable solution. 
@filipe-cantarelli 👍 

 submitted #67

**Comment by ViliusS** [comment]
@loburm will this ever be fixed? This constantly bites us in the $%&.

For example, we've been running [RabbitMQ Cluster from Google Marketplace](https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md), which installs with prometheus-to-sd as sidecar container and configures metric descriptors as int64 values.
Now we want to monitor our RabbitMQ clients (Java applications), which uses Spring Boot GCP libraries and configures metric descriptors as double values. The application runs in the same GCP project on GKE.
Coincidently both, RabbitMQ cluster and RabbitMQ client applications, have two metrics under the same name: `custom.googleapi.com/rabbitmq/connections` and `custom.googleapi.com/rabbitmq/channels`. Since prometheus-to-sd created metric descriptors with INT64 we cannot collect these metrics from Java application. We also cannot change metric descriptor because it comes from Spring Boot and/or GCP libraries. The following error is produced:
```
failed to send metrics to Stackdriver
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: timeSeries[62] (metric.type="custom.googleapis.com/rabbitmq/connections", metric.labels={"application": "client-comm", "name": "rabbit", "instance": "client-comm-56cc876f75-4vjb6"}, resource.type="global", resource.labels={"project_id": "testproject"}): value type for metric conflicts with the existing value type (INT64); timeSeries[0] (metric.type="custom.googleapis.com/rabbitmq/channels", metric.labels={"instance": "client-comm-56cc876f75-4vjb6", "name": "rabbit", "application": "client-comm"}, resource.type="global", resource.labels={"project_id": "testproject"}): value type for metric conflicts with the existing value type (INT64)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1729)
		at io.micrometer.stackdriver.StackdriverMeterRegistry.publish(StackdriverMeterRegistry.java:175)
		at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:59)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
		... 3 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: timeSeries[62] (metric.type="custom.googleapis.com/rabbitmq/connections", metric.labels={"application": "client-comm", "name": "rabbit", "instance": "client-comm-56cc876f75-4vjb6"}, resource.type="global", resource.labels={"project_id": "testproject"}): value type for metric conflicts with the existing value type (INT64); timeSeries[0] (metric.type="custom.googleapis.com/rabbitmq/channels", metric.labels={"instance": "client-comm-56cc876f75-4vjb6", "name": "rabbit", "application": "client-comm"}, resource.type="global", resource.labels={"project_id": "testproject"}): value type for metric conflicts with the existing value type (INT64)
	at io.grpc.Status.asRuntimeException(Status.java:537)
	... 14 common frames omitted
```

If default value type cannot be changed then maybe it could be hidden behind feature gate like in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/googlemanagedprometheusexporter/README.md#feature-gates ?

**Comment by loburm** [comment]
I'm not working on this project anymore. @erain do we still use prometheus-to-sd anywhere in GKE?
